/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TraumaRouteImport } from './routes/trauma'
import { Route as TermsOfUseRouteImport } from './routes/terms-of-use'
import { Route as SportsInjuryRouteImport } from './routes/sports-injury'
import { Route as SpecializationsRouteImport } from './routes/specializations'
import { Route as ShoulderElbowRouteImport } from './routes/shoulder-elbow'
import { Route as ShoulderRouteImport } from './routes/shoulder'
import { Route as RoboticSurgeryRouteImport } from './routes/robotic-surgery'
import { Route as RoboticKneeRouteImport } from './routes/robotic-knee'
import { Route as RoboticHipRouteImport } from './routes/robotic-hip'
import { Route as ProceduresRouteImport } from './routes/procedures'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PatientResourcesRouteImport } from './routes/patient-resources'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as KneeRouteImport } from './routes/knee'
import { Route as HipRouteImport } from './routes/hip'
import { Route as ElbowRouteImport } from './routes/elbow'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CitiesRouteImport } from './routes/cities'
import { Route as ArthroscopyRouteImport } from './routes/arthroscopy'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConditionsIndexRouteImport } from './routes/conditions.index'
import { Route as CitiesIndexRouteImport } from './routes/cities.index'
import { Route as ProceduresSlugRouteImport } from './routes/procedures.$slug'
import { Route as ConditionsSlugRouteImport } from './routes/conditions.$slug'
import { Route as CitiesSlugRouteImport } from './routes/cities.$slug'

const TraumaRoute = TraumaRouteImport.update({
  id: '/trauma',
  path: '/trauma',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfUseRoute = TermsOfUseRouteImport.update({
  id: '/terms-of-use',
  path: '/terms-of-use',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsInjuryRoute = SportsInjuryRouteImport.update({
  id: '/sports-injury',
  path: '/sports-injury',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecializationsRoute = SpecializationsRouteImport.update({
  id: '/specializations',
  path: '/specializations',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoulderElbowRoute = ShoulderElbowRouteImport.update({
  id: '/shoulder-elbow',
  path: '/shoulder-elbow',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoulderRoute = ShoulderRouteImport.update({
  id: '/shoulder',
  path: '/shoulder',
  getParentRoute: () => rootRouteImport,
} as any)
const RoboticSurgeryRoute = RoboticSurgeryRouteImport.update({
  id: '/robotic-surgery',
  path: '/robotic-surgery',
  getParentRoute: () => rootRouteImport,
} as any)
const RoboticKneeRoute = RoboticKneeRouteImport.update({
  id: '/robotic-knee',
  path: '/robotic-knee',
  getParentRoute: () => rootRouteImport,
} as any)
const RoboticHipRoute = RoboticHipRouteImport.update({
  id: '/robotic-hip',
  path: '/robotic-hip',
  getParentRoute: () => rootRouteImport,
} as any)
const ProceduresRoute = ProceduresRouteImport.update({
  id: '/procedures',
  path: '/procedures',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientResourcesRoute = PatientResourcesRouteImport.update({
  id: '/patient-resources',
  path: '/patient-resources',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const KneeRoute = KneeRouteImport.update({
  id: '/knee',
  path: '/knee',
  getParentRoute: () => rootRouteImport,
} as any)
const HipRoute = HipRouteImport.update({
  id: '/hip',
  path: '/hip',
  getParentRoute: () => rootRouteImport,
} as any)
const ElbowRoute = ElbowRouteImport.update({
  id: '/elbow',
  path: '/elbow',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesRoute = CitiesRouteImport.update({
  id: '/cities',
  path: '/cities',
  getParentRoute: () => rootRouteImport,
} as any)
const ArthroscopyRoute = ArthroscopyRouteImport.update({
  id: '/arthroscopy',
  path: '/arthroscopy',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsIndexRoute = ConditionsIndexRouteImport.update({
  id: '/conditions/',
  path: '/conditions/',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesIndexRoute = CitiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CitiesRoute,
} as any)
const ProceduresSlugRoute = ProceduresSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProceduresRoute,
} as any)
const ConditionsSlugRoute = ConditionsSlugRouteImport.update({
  id: '/conditions/$slug',
  path: '/conditions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesSlugRoute = CitiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CitiesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/arthroscopy': typeof ArthroscopyRoute
  '/cities': typeof CitiesRouteWithChildren
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/elbow': typeof ElbowRoute
  '/hip': typeof HipRoute
  '/knee': typeof KneeRoute
  '/locations': typeof LocationsRoute
  '/patient-resources': typeof PatientResourcesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/procedures': typeof ProceduresRouteWithChildren
  '/robotic-hip': typeof RoboticHipRoute
  '/robotic-knee': typeof RoboticKneeRoute
  '/robotic-surgery': typeof RoboticSurgeryRoute
  '/shoulder': typeof ShoulderRoute
  '/shoulder-elbow': typeof ShoulderElbowRoute
  '/specializations': typeof SpecializationsRoute
  '/sports-injury': typeof SportsInjuryRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/trauma': typeof TraumaRoute
  '/cities/$slug': typeof CitiesSlugRoute
  '/conditions/$slug': typeof ConditionsSlugRoute
  '/procedures/$slug': typeof ProceduresSlugRoute
  '/cities/': typeof CitiesIndexRoute
  '/conditions/': typeof ConditionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/arthroscopy': typeof ArthroscopyRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/elbow': typeof ElbowRoute
  '/hip': typeof HipRoute
  '/knee': typeof KneeRoute
  '/locations': typeof LocationsRoute
  '/patient-resources': typeof PatientResourcesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/procedures': typeof ProceduresRouteWithChildren
  '/robotic-hip': typeof RoboticHipRoute
  '/robotic-knee': typeof RoboticKneeRoute
  '/robotic-surgery': typeof RoboticSurgeryRoute
  '/shoulder': typeof ShoulderRoute
  '/shoulder-elbow': typeof ShoulderElbowRoute
  '/specializations': typeof SpecializationsRoute
  '/sports-injury': typeof SportsInjuryRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/trauma': typeof TraumaRoute
  '/cities/$slug': typeof CitiesSlugRoute
  '/conditions/$slug': typeof ConditionsSlugRoute
  '/procedures/$slug': typeof ProceduresSlugRoute
  '/cities': typeof CitiesIndexRoute
  '/conditions': typeof ConditionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/arthroscopy': typeof ArthroscopyRoute
  '/cities': typeof CitiesRouteWithChildren
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/elbow': typeof ElbowRoute
  '/hip': typeof HipRoute
  '/knee': typeof KneeRoute
  '/locations': typeof LocationsRoute
  '/patient-resources': typeof PatientResourcesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/procedures': typeof ProceduresRouteWithChildren
  '/robotic-hip': typeof RoboticHipRoute
  '/robotic-knee': typeof RoboticKneeRoute
  '/robotic-surgery': typeof RoboticSurgeryRoute
  '/shoulder': typeof ShoulderRoute
  '/shoulder-elbow': typeof ShoulderElbowRoute
  '/specializations': typeof SpecializationsRoute
  '/sports-injury': typeof SportsInjuryRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/trauma': typeof TraumaRoute
  '/cities/$slug': typeof CitiesSlugRoute
  '/conditions/$slug': typeof ConditionsSlugRoute
  '/procedures/$slug': typeof ProceduresSlugRoute
  '/cities/': typeof CitiesIndexRoute
  '/conditions/': typeof ConditionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/arthroscopy'
    | '/cities'
    | '/contact'
    | '/disclaimer'
    | '/elbow'
    | '/hip'
    | '/knee'
    | '/locations'
    | '/patient-resources'
    | '/privacy-policy'
    | '/procedures'
    | '/robotic-hip'
    | '/robotic-knee'
    | '/robotic-surgery'
    | '/shoulder'
    | '/shoulder-elbow'
    | '/specializations'
    | '/sports-injury'
    | '/terms-of-use'
    | '/trauma'
    | '/cities/$slug'
    | '/conditions/$slug'
    | '/procedures/$slug'
    | '/cities/'
    | '/conditions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/arthroscopy'
    | '/contact'
    | '/disclaimer'
    | '/elbow'
    | '/hip'
    | '/knee'
    | '/locations'
    | '/patient-resources'
    | '/privacy-policy'
    | '/procedures'
    | '/robotic-hip'
    | '/robotic-knee'
    | '/robotic-surgery'
    | '/shoulder'
    | '/shoulder-elbow'
    | '/specializations'
    | '/sports-injury'
    | '/terms-of-use'
    | '/trauma'
    | '/cities/$slug'
    | '/conditions/$slug'
    | '/procedures/$slug'
    | '/cities'
    | '/conditions'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/arthroscopy'
    | '/cities'
    | '/contact'
    | '/disclaimer'
    | '/elbow'
    | '/hip'
    | '/knee'
    | '/locations'
    | '/patient-resources'
    | '/privacy-policy'
    | '/procedures'
    | '/robotic-hip'
    | '/robotic-knee'
    | '/robotic-surgery'
    | '/shoulder'
    | '/shoulder-elbow'
    | '/specializations'
    | '/sports-injury'
    | '/terms-of-use'
    | '/trauma'
    | '/cities/$slug'
    | '/conditions/$slug'
    | '/procedures/$slug'
    | '/cities/'
    | '/conditions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ArthroscopyRoute: typeof ArthroscopyRoute
  CitiesRoute: typeof CitiesRouteWithChildren
  ContactRoute: typeof ContactRoute
  DisclaimerRoute: typeof DisclaimerRoute
  ElbowRoute: typeof ElbowRoute
  HipRoute: typeof HipRoute
  KneeRoute: typeof KneeRoute
  LocationsRoute: typeof LocationsRoute
  PatientResourcesRoute: typeof PatientResourcesRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProceduresRoute: typeof ProceduresRouteWithChildren
  RoboticHipRoute: typeof RoboticHipRoute
  RoboticKneeRoute: typeof RoboticKneeRoute
  RoboticSurgeryRoute: typeof RoboticSurgeryRoute
  ShoulderRoute: typeof ShoulderRoute
  ShoulderElbowRoute: typeof ShoulderElbowRoute
  SpecializationsRoute: typeof SpecializationsRoute
  SportsInjuryRoute: typeof SportsInjuryRoute
  TermsOfUseRoute: typeof TermsOfUseRoute
  TraumaRoute: typeof TraumaRoute
  ConditionsSlugRoute: typeof ConditionsSlugRoute
  ConditionsIndexRoute: typeof ConditionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trauma': {
      id: '/trauma'
      path: '/trauma'
      fullPath: '/trauma'
      preLoaderRoute: typeof TraumaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-use': {
      id: '/terms-of-use'
      path: '/terms-of-use'
      fullPath: '/terms-of-use'
      preLoaderRoute: typeof TermsOfUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports-injury': {
      id: '/sports-injury'
      path: '/sports-injury'
      fullPath: '/sports-injury'
      preLoaderRoute: typeof SportsInjuryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specializations': {
      id: '/specializations'
      path: '/specializations'
      fullPath: '/specializations'
      preLoaderRoute: typeof SpecializationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shoulder-elbow': {
      id: '/shoulder-elbow'
      path: '/shoulder-elbow'
      fullPath: '/shoulder-elbow'
      preLoaderRoute: typeof ShoulderElbowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shoulder': {
      id: '/shoulder'
      path: '/shoulder'
      fullPath: '/shoulder'
      preLoaderRoute: typeof ShoulderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robotic-surgery': {
      id: '/robotic-surgery'
      path: '/robotic-surgery'
      fullPath: '/robotic-surgery'
      preLoaderRoute: typeof RoboticSurgeryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robotic-knee': {
      id: '/robotic-knee'
      path: '/robotic-knee'
      fullPath: '/robotic-knee'
      preLoaderRoute: typeof RoboticKneeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robotic-hip': {
      id: '/robotic-hip'
      path: '/robotic-hip'
      fullPath: '/robotic-hip'
      preLoaderRoute: typeof RoboticHipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procedures': {
      id: '/procedures'
      path: '/procedures'
      fullPath: '/procedures'
      preLoaderRoute: typeof ProceduresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient-resources': {
      id: '/patient-resources'
      path: '/patient-resources'
      fullPath: '/patient-resources'
      preLoaderRoute: typeof PatientResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knee': {
      id: '/knee'
      path: '/knee'
      fullPath: '/knee'
      preLoaderRoute: typeof KneeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hip': {
      id: '/hip'
      path: '/hip'
      fullPath: '/hip'
      preLoaderRoute: typeof HipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elbow': {
      id: '/elbow'
      path: '/elbow'
      fullPath: '/elbow'
      preLoaderRoute: typeof ElbowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities': {
      id: '/cities'
      path: '/cities'
      fullPath: '/cities'
      preLoaderRoute: typeof CitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arthroscopy': {
      id: '/arthroscopy'
      path: '/arthroscopy'
      fullPath: '/arthroscopy'
      preLoaderRoute: typeof ArthroscopyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions/': {
      id: '/conditions/'
      path: '/conditions'
      fullPath: '/conditions/'
      preLoaderRoute: typeof ConditionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities/': {
      id: '/cities/'
      path: '/'
      fullPath: '/cities/'
      preLoaderRoute: typeof CitiesIndexRouteImport
      parentRoute: typeof CitiesRoute
    }
    '/procedures/$slug': {
      id: '/procedures/$slug'
      path: '/$slug'
      fullPath: '/procedures/$slug'
      preLoaderRoute: typeof ProceduresSlugRouteImport
      parentRoute: typeof ProceduresRoute
    }
    '/conditions/$slug': {
      id: '/conditions/$slug'
      path: '/conditions/$slug'
      fullPath: '/conditions/$slug'
      preLoaderRoute: typeof ConditionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities/$slug': {
      id: '/cities/$slug'
      path: '/$slug'
      fullPath: '/cities/$slug'
      preLoaderRoute: typeof CitiesSlugRouteImport
      parentRoute: typeof CitiesRoute
    }
  }
}

interface CitiesRouteChildren {
  CitiesSlugRoute: typeof CitiesSlugRoute
  CitiesIndexRoute: typeof CitiesIndexRoute
}

const CitiesRouteChildren: CitiesRouteChildren = {
  CitiesSlugRoute: CitiesSlugRoute,
  CitiesIndexRoute: CitiesIndexRoute,
}

const CitiesRouteWithChildren =
  CitiesRoute._addFileChildren(CitiesRouteChildren)

interface ProceduresRouteChildren {
  ProceduresSlugRoute: typeof ProceduresSlugRoute
}

const ProceduresRouteChildren: ProceduresRouteChildren = {
  ProceduresSlugRoute: ProceduresSlugRoute,
}

const ProceduresRouteWithChildren = ProceduresRoute._addFileChildren(
  ProceduresRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ArthroscopyRoute: ArthroscopyRoute,
  CitiesRoute: CitiesRouteWithChildren,
  ContactRoute: ContactRoute,
  DisclaimerRoute: DisclaimerRoute,
  ElbowRoute: ElbowRoute,
  HipRoute: HipRoute,
  KneeRoute: KneeRoute,
  LocationsRoute: LocationsRoute,
  PatientResourcesRoute: PatientResourcesRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProceduresRoute: ProceduresRouteWithChildren,
  RoboticHipRoute: RoboticHipRoute,
  RoboticKneeRoute: RoboticKneeRoute,
  RoboticSurgeryRoute: RoboticSurgeryRoute,
  ShoulderRoute: ShoulderRoute,
  ShoulderElbowRoute: ShoulderElbowRoute,
  SpecializationsRoute: SpecializationsRoute,
  SportsInjuryRoute: SportsInjuryRoute,
  TermsOfUseRoute: TermsOfUseRoute,
  TraumaRoute: TraumaRoute,
  ConditionsSlugRoute: ConditionsSlugRoute,
  ConditionsIndexRoute: ConditionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
